name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          
      - name: Gerar function.zip
        run: |
          cd lambda/create_payment
          zip function.zip index.js

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Exportar variáveis do Terraform
        run: |
          echo "TF_VAR_cloudflare_api_token=${{ secrets.cloudflare_api_token }}" >> $GITHUB_ENV
          echo "TF_VAR_cloudflare_zone_id=${{ secrets.cloudflare_zone_id }}" >> $GITHUB_ENV
          echo "TF_VAR_domain_name=mazzotti.app" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform -chdir=infra init -reconfigure

      - name: Terraform Destroy
        run: terraform -chdir=infra destroy -auto-approve
